version: "3"
services:
  memgraph-mage:
    image: memgraph/memgraph-mage:1.1
    user: memgraph
    volumes:
      - ./memgraph/import-data:/usr/lib/memgraph/import-data
    ports:
      - "7687:7687"
  protein-explorer:
    build: ./explorer
    volumes:
      - ./explorer:/app
    ports:
      - "5000:5000"
    environment:
      MG_HOST: memgraph-mage
      MG_PORT: 7687
    depends_on:
      - memgraph-mage
