version: "3"
services:
  memgraph-mage:
    image: memgraph:mage 
    user: root
    volumes:
        - ./memgraph/entrypoint:/usr/lib/memgraph/entrypoint
        - ./memgraph/import-data:/usr/lib/memgraph/import-data
        - ./memgraph/mg_log:/var/log/memgraph
        - ./memgraph/mg_etc:/etc/memgraph
    ports:
      - "7687:7687"
  protein-explorer:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      MG_HOST: memgraph-mage
      MG_PORT: 7687
    depends_on:
      - memgraph-mage
